djangoclasscrud/app/urls.py
from django.contrib import admin
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('update/<int:pk>', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.SchoolDeleteView.as_view(), name='delete'),
]

djangoclasscrud/djangoclasscrud/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views

urlpatterns = [
    path('',views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]

djangoclasscrud/app/models.py
from django.db import models
from django.urls import reverse


class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse("app:detail", kwargs={'pk':self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    School = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)


    def __str__(self):
        return self.name

djangoclasscrud/app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import (View, TemplateView, ListView, DetailView, CreateView, DeleteView, UpdateView)
from . import models


# just index 
class IndexView(TemplateView):
    template_name = 'app/index.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['hereval'] = "HERE IS SERVER SIDE VALUE"
        return context


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School
    template_name = 'app/school_list.html'

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ("name", "principal", "location")
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ("name", "principal")
    model = models.School
    template_name = 'app/school_form.html'

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("app:list")

class CBView(View):
    def get(self,request):
        return HttpResponse('Class Based View are Cool!')

djangoclasscrud/app/templates/app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>
      CBVs
      {# Title Extensions go inside the block#}
      {% block title_block %}

      {% endblock %}
    </title>

    {# Bootstrap and CSS (Probably would want downloaded files in your real projects)#}
    {# https://bootswatch.com/#}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
          
        </ul>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

  {# Plugins#}


  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script
  src="https://code.jquery.com/jquery-3.2.0.min.js"
  integrity="sha256-JAW99MJVpJBGcbzEuXk4Az05s/XyDdBomFqNlM3ic+I="
  crossorigin="anonymous"></script>
</html>

djangoclasscrud/app/templates/app/basic_app_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>BASE!</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'app:list' %}">Schools</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
        <li><a class="navbar-link" href="{% url 'app:list' %}">Schools</a></li>


      </ul>

    </nav>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

djangoclasscrud/app/templates/app/index.html
{% extends "app/base.html" %}

  {% block body_block %}
    <h1>Welcome to the index page!</h1>
    <h2>Here is your injected content: {{ hereval }}</h2>
  {% endblock %}

djangoclasscrud/app/templates/app/school_confirm_delete.html
{% extends "app/basic_app_base.html" %}
{% block body_block %}
  <h1>Delete {{school.name}}?</h1>

  <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <!-- NOTE: here we must pass the pk=school.pk because in the basic_app:detail view, in urls.py
    the regex expects a primary key value (pk) -->
    <a href="{% url 'app:detail' pk=school.pk %}">Cancel</a>
  </form>
{% endblock %}

djangoclasscrud/app/templates/app/school_detail.html
{% extends 'app/basic_app_base.html' %}

{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to the School Detailed page!</h1>
  <h2>School details:</h2>
  <p>Name: {{school_detail.name}}</p>
  <p>Principal: {{school_detail.principal}}</p>
  <p>Location: {{school_detail.location}}</p>

  <h3>Students</h3>
  {% for student in school_detail.students.all %}
    <p>{{student.name}} who is {{student.age}} years old.</p>
  {% endfor %}
</div>

<div class="container">
  <p><a class="btn btn-warning" href="{% url 'app:update' pk=school_detail.pk%}">Update</a></p>
  <p><a class="btn btn-danger" href="{% url 'app:delete' pk=school_detail.pk%}">Delete</a></p>

</div>

{% endblock %}

djangoclasscrud/app/templates/app/school_form.html
{% extends "app/basic_app_base.html" %}
{% block body_block %}
  <h1>
    {% if not form.instance.pk %}
      Create school
    {% else %}
      Update school
    {% endif %}
  </h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="btn btn-primary" value="Submit">
  </form>
{% endblock %}

djangoclasscrud/app/templates/app/school_list.html
{% extends "app/basic_app_base.html" %}

{% block body_block %}
  <h1> Wecome to a list of all the schools!</h1>
  <ol>
    {% for school in schools %}
      <h2><li><a href="{{school.pk}}">{{school.name}}</a></li></h2>
    {% endfor %}
  </ol>
{% endblock %}